### ISSUE TITLE
Select a CMS for guides

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#1]
As a Bloomer, I want a way to easily write, publish, and manage changes for guides around how we work as a company.

# Good Things to Eval

- Ease of standing up a new site
- Ease of adding a style/CSS library
- Ease of adding a frontend JS library
- Ease of theming (stretch: is there a theme ecosystem)
- Sustainability of platform's development (i.e. if an open source project, how is it maintained / is it maintained?)

# Other Notes

- Would be good to select a static site generator that can leverage GitHub's PR workfow for change management AND be easy for non-developers to navigate and work within. 
- Two CMSes we've already explored, but opted against is Gatsby (heavy, hard to maintain, and not liked by clients) and Jekyll (open source project seems like it's on a down spiral). 
- Two compelling options are Eleventy (used by Corey and California ODI) and Hugo (looks like [18F is toying with moving their guides to this](https://github.com/18F/guides-and-methods-hugo))

# Done when

- [x] A CMS has been selected
- [x] A new Eleventy project is generated and committed to the repo
- [x] The reasons for selecting that CMS have been documented in a decision doc

# Meeting Notes

## May 30, 2023

- Makai: Stick with Netlify for hosting and leaning towards Eleventy, but playing with Hugo.

**Comment by jeffmaher** [comment]
June 1 update:
- Makai has tried out Eleventy, and just needs to try Hugo
- Leaning towards Eleventy

**Comment by jeffmaher** [comment]
Notes for 6/6:

- Eleventy is the choice
- Moving back to ready, so that we can prioritize work with Josh. Documentation to come later.
- Still to do: Create a starter for Eleventy in the guides-template repo

**Comment by jeffmaher** [comment]
Notes from 6/8:

- Makai and Jeff to meet tomorrow to get Eleventy in
- Will return to backlog for decision doc later

**Comment by admoorgit** [comment]
Notes from 06/13:

- Need to set up pipelines
- Need to push to Git
- Add Eleventy Template

**Comment by admoorgit** [comment]
Notes from 06/15:
• Makai has this up and working!

**Comment by jeffmaher** [comment]
Only item remaining is to document the decision.

**Comment by jeffmaher** [comment]
@SMakaiTakori : Reviewed [the decision doc](https://docs.google.com/document/d/199VYM7Tnf_0VlFY1LDAoufAcy8iOPG8GugFPA8eS3ic/edit#heading=h.o0nvkdv8zref) and it looks great! Made one suggested edit and would be great to move it into the [new decision docs folder](https://drive.google.com/drive/u/0/folders/1b-TGgadR9-OXoju2OHOhks2vfViNZsAT?lfhs=2).
