### ISSUE TITLE
Component: Three-column Grid

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#16]
# Stories

- As a reader of a guide, I want to see grids so that I can get easy to understand summarizes of information.

# Notes

- See [the component doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit#heading=h.hns2k9p106d4) for more information
- This ticket covers both design and development tasks. Change assignee of the ticket based on who has the next action, and remove the person or people that no longer have an action. It's expected that a ticket will get passed back and forth a few times.

# Done When

- [ ] UX: Component design is drafted and shared for review
- [ ] Dev: Component design is reviewed and approved
- [ ] Peer UX: Compontent design is reviewed and approved
- [ ] Dev: Component style and markup is developed and shared for PR review
- [ ] Dev: Documentation on how to use component is drafted
- [ ] UX: Component style and markup is reviewed and approved
- [ ] Peer Dev: Component style and markup is reviewed and approved
- [ ] Component is available for use

**Comment by jrubenoff** [comment]
@jeffmaher I'm assuming the grid should have nearly identical markup and visual styles no matter how many columns it has, so perhaps it makes sense to combine this with #15?

**Comment by jeffmaher** [comment]
> @jeffmaher I'm assuming the grid should have nearly identical markup and visual styles no matter how many columns it has, so perhaps it makes sense to combine this with #15?

Sounds good! Let's track there. I'll adjust the tickets.
