### ISSUE TITLE
Decide on content types / kinds of pages

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#2]
As a reader of a guide, I want content to be presented to me in a clear and readable format so that I can follow and understand it.

As a Bloomer writing a guide, I want to be able to compose content in a format that meets my context so that my text and media can be displayed appropriately without having to recreate the format for every page.

As the designer of Bloom guides, I want to know what kind of material will initially be published using the guides design so that that content can be usable, visually appealing, and on-brand.

# Done When

## Source Material Review

- [x] Review [current handbook](https://bloom-handbook.readthedocs.io/en/latest/)
- [x] Review [proposed handbook](https://docs.google.com/document/d/1IWmW3pYjCnryU8rEQeenjtBX7VtvQeL-4AfVJHcyPXc/edit)
- [x] Review [discovery sprint playbook draft](https://docs.google.com/document/d/1uftXjCD_j2YPdx67tSyVIzzZaA97vYCZxcp2EE25tRw/edit#heading=h.o0nvkdv8zref)
- [x] Review [organs report](https://bloomworks.digital/organdonationreform)
- [x] Review [Bloom Website](https://bloomworks.digital) for brand look-and-feel
- [x] Chat with Adam for brand guidance

## Content Types Design

- [x] Content types / kinds of pages are proposed
- [x] Content types are discussed
- [x] Content types are approved by the team
- [x] Tasks to implement the content types are created

**Comment by jeffmaher** [comment]
June 1:
- Josh looking into
- Things Josh needs access to is new employee handbook draft
- Made a list of content types
- Josh to commit a draft to the repo

**Comment by jrubenoff** [comment]
## Progress this week

- [I wrote up a Google Doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit?usp=sharing) with a rough component inventory, alongside suggestions for new components and pages. Feel free to comment and critique!

- I just pushed up a `storybook` branch to this repo with _very_ rough HTML / CSS sketches of these components.  @SMakaiTakori Happy to delete all of this if there's another way you'd prefer to collaborate. It might be good to meet next week and talk about ways to work together!

## Open-ended questions for team discussion

1. How does the list of components in the Google Doc sound? Do any feel unnecessary or over-designed? Is there anything we feel is missing?
2. I noticed the organ donation site doesn't use Bloom's brand colors. Are we looking to add custom themes to our guides for different clients?
3. Are these guides meant for casual reference or for frequent use? To frame it another way: Should the design make it easiest to quickly find a specific passage when you just want to look something up? Should it encourage deep engagement with the text and long session times? Or are we aiming for somewhere in the middle?

## Closed-ended questions

4. Do we have an easy way to convert GDocs to Markdown, or is the plan to do it all manually?

5. There is one [nested checklist at the end of the discovery playbook](https://docs.google.com/document/d/1uftXjCD_j2YPdx67tSyVIzzZaA97vYCZxcp2EE25tRw/edit#heading=h.hjqs3ttpjgyn) which seems a little harder to style and maintain, especially on smaller screens. Would we be OK with flattening all checklists to one level?

6. @admoorgit Does Bloom have a preferred icon set? I used [Bootstrap Icons](https://icons.getbootstrap.com/) this week but am happy to switch to whatever you'd prefer.

**Comment by jeffmaher** [comment]
Notes from 6/6:

- @SMakaiTakori and @jrubenoff to chat about how to collaborate on styles
- @jeffmaher to review @jrubenoff 's document for Wed morning

**Comment by jrubenoff** [comment]
To close the loop: I met with Adam this morning and got clarity around icons. (We mostly use Noun Project's, but Bootstrap Icons works as well.)

**Comment by jeffmaher** [comment]
Notes from 6/8:

- Josh and Adam chatted, and some different opinions between Adam and Jeff
- Josh is working on prototyping some things in Storybook
- @jeffmaher Need to create tickets for the inscope things in the document

**Comment by admoorgit** [comment]
Notes from 06/13:
DONE!
