### ISSUE TITLE
Design intra-guide navigation

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#4]
As a guide reader, I want to be able to find content within a guide so that I can answer questions I have about how Bloom works.

# Done When

- [ ] Navigation design mockup created
- [ ] Navigation design mockup reviewed and approved by the team
- [ ] Navigation design implementation tickets created

**Comment by jrubenoff** [comment]
@jeffmaher Not sure how this differs from #8 or #9! Any chance you can clarify?

**Comment by jeffmaher** [comment]
@jrubenoff : Sorry for the delayed response! This is the page that would be on https://bloomworks.digital that would link to the various guides. No rush to get into scope during June though, and we can take this up later.
