### ISSUE TITLE
Setup guides repo (template task)

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#5]
# Stories

As a guides writer, I want to be able to easily write, edit, and collaborate on guide content so that I can share what I've learned.

As a guides developer, I want my repo to be setup for users to easily find files, clear change management workflows, preview environments, and automatic deployments so that I can save time on manual tasks and enable users to work without deep technical knowledge.

# Done When

- [x] Repo is created
- [x] Developer setup instructions are documented
- [x] License is documented
- [x] Documentation exists to tell users how to modify files and where those files live (Est: Small - 2h)
- [x] Code Owners is configured to require the relevant reviews
- [x] Protected branches configured
- [x] Preview environments are deployed when PRs are submitted, changed and are deleted when the PR is closed
- [x] The default branch is deployed when a PR is merged
- [x] Blocking automated code style tests are run in PRs (Est: Large - 8h)
- [x] Blocking automated accessibility tests are run in PRs (Est: Medium - 4h)
- [x] Idempotent builds configured (i.e. dependencies are fixed)

**Comment by jeffmaher** [comment]
Turned on branch protection rules, and recorded a short explainer video on the settings. It wouldn't upload here (too big), so dropping into [our website Slack channel](https://govbloomdigital.slack.com/archives/C01CYR2A21X/p1687213945365029). cc @SMakaiTakori

**Comment by jeffmaher** [comment]
@jrubenoff , @SMakaiTakori : I think the repo is pretty setup, such that other PRs can start coming in. Things are configured to require 2 reviewers (designer + developer).

**Comment by SMakaiTakori** [comment]
@jeffmaher I would like to go ahead and [set up this GH workflow](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#example-using-npm) but I wanted to check in to make sure I am on the right track with what you were thinking for the automated tests.

**Comment by jeffmaher** [comment]
- Getting closer Playwright tests working
- Next step is the accessibility tests

**Comment by SMakaiTakori** [comment]
@SMakaiTakori will merge in JS Linter today and will also push a PR for accessibility tests when done. Also, spoke with @jeffmaher and we will wait to do documentation for file changes once this repo is copied over to the handbook.

@LynnHerrick9 will look at updating nunjucks linter and style linters and will tag @SMakaiTakori when done.

**Comment by jeffmaher** [comment]
Per @SMakaiTakori : 

- Working on accessibility test and documentation for where files go. 
- Chat with Josh on where files go.
- Josh added some example files too

**Comment by jeffmaher** [comment]
- Remaining accessibility work being covered in #53 
- @LynnHerrick9 : Remaining task is the documentation on how to add/find/edit a page to the guide.

**Comment by jeffmaher** [comment]
Update from weekly meeting:

- Update in from Lynn
- Makai working on the documentation on how to add a file

**Comment by jeffmaher** [comment]
Makai wrote documentation on adding new files. We can expand over time and will add some items to the backlog, but good for getting things started.
