### ISSUE TITLE
Component: Site Navigation

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#8]
# Stories

- As a reader of a guide, I want to see what sections are in the guide so that I know if the guide is relevant and has what I'm trying to learn.
- As a reader of a guide, I want to be able to navigate around so that I can get to the information I'm looking for.

# Notes

- This ticket covers both design and development tasks. Change assignee of the ticket based on who has the next action, and remove the person or people that no longer have an action. It's expected that a ticket will get passed back and forth a few times.
- See the [component doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit#heading=h.yuzn4ifuwtwx) for more information

# Done When

- [x] UX: Component design is drafted and shared for review
- [x] Dev: Component design is reviewed and approved
- [ ] Peer UX: Compontent design is reviewed and approved
- [ ] Dev: Component style and markup is developed and shared for PR review
- [ ] Dev: Documentation on how to use component is drafted
- [ ] UX: Component style and markup is reviewed and approved
- [ ] Peer Dev: Component style and markup is reviewed and approved
- [ ] Component is available for use

**Comment by jrubenoff** [comment]
### Context

I wrote [in the GDoc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit) that this component should have:

> - The name of the guide
> - Links to every section of the guide
> - A "back to all guides" link

### Design constraints

- The guide's name can be quite long. (Like: "The Costly Effects of an Outdated Organ Donation System.")
- A guide can have many sections. (The employee handbook has 23.)

### Researching navigation design patterns for web-based e-books

I looked at:

- [The Manifold platform (for university presses)](https://publish.iupress.indiana.edu/read/black-film-as-genre/section/5789a362-45ee-430c-8dca-68878f3b1314#ch2)
- [The Data Journalism Verification Handbook](https://datajournalism.com/read/handbook/verification-3/investigating-disinformation-and-media-manipulation/investigating-disinformation)
- [Resilient Web Design](https://resilientwebdesign.com/)
- [Make Something Wonderful](https://book.stevejobsarchive.com/)
- [The Raster Tragedy (very basic design)](http://rastertragedy.com/RTRCh0.htm)
- [Perfect Edition](https://github.com/robinsloan/perfect-edition)

Some of them display the guide's sections in a sidebar. But the sidebar inevitably competes with the main content for attention, especially when there are many sections, like in Raster Tragedy.

![CleanShot 2023-06-14 at 18 32 16@2x](https://github.com/bloom-works/guides-template/assets/1328849/6e231ece-5870-4673-a58c-1daf338415b3)

Others use this floating sidebar modal. Although it looks nice, it isn't super clear at a glance which layer is "on top," like this example from Manifold:

<img width="1061" alt="CleanShot 2023-06-14 at 19 43 41@2x" src="https://github.com/bloom-works/guides-template/assets/1328849/6d855a6a-e23d-4e1c-8c32-b9021d1cd4a3">

Perfect Edition has this really nice sense of dimensionality to its navigation modal. It makes the UI's current state extremely clear. But it appears to be inaccessible to screen readers:

<img width="726" alt="CleanShot 2023-06-14 at 19 46 48@2x" src="https://github.com/bloom-works/guides-template/assets/1328849/631cc255-8a8f-43e0-8d5c-8196ad93bfaf">

Thus...

### Design principles for navigation

- Make it easy for readers to jump to any section of the guide
- Minimize distractions for people while they're reading
- Make the current UI state extremely clear
- Make it accessible

### Markup

As of 2023, the [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element seems like it fulfills all of the above criteria. Here's a blog post from [Scott O'Hara](https://www.scottohara.me/blog/2023/01/26/use-the-dialog-element.html) encouraging its use.

### Visual design

Here's what I have right now:

#### Smaller screens

<img width="326" alt="CleanShot 2023-06-14 at 18 18 14@2x" src="https://github.com/bloom-works/guides-template/assets/1328849/4208b85a-c026-415b-8b04-e652383cfbbf">

#### Larger screens

<img width="956" alt="CleanShot 2023-06-14 at 18 19 24@2x" src="https://github.com/bloom-works/guides-template/assets/1328849/29095c54-887d-4836-8a0b-6a1e268f63bf">

---

Here's what it looks like with a long title:

![CleanShot 2023-06-14 at 18 23 14@2x](https://github.com/bloom-works/guides-template/assets/1328849/74b0e66a-2317-40ae-9325-b0a9d709f528)

When you click "Chapters," the `<dialog>` element appears. Here's how I've styled it:

<img width="1493" alt="CleanShot 2023-06-14 at 18 26 33@2x" src="https://github.com/bloom-works/guides-template/assets/1328849/fa8228af-399a-4af2-afec-db16d6e497f1">

---

### Notes

- Depending on the provider we choose, the Search button might trigger a modal or link to a dedicated search page. (See #18 for more info.)
- I assume it's OK to omit "Bloom Works" from the logo, for the sake of saving space. Let me know if you disagree.
- When I showed this to @admoorgit, he wanted to ensure the reader understood they could scroll within the modal. I'll experiment with styling to help the user understand where overflow content exists.

---

### Status

I'll soon commit an example of this component to the `storybook` branch. Once #5 and #6 are done, I can open a PR with just this component for review.

@jeffmaher @SMakaiTakori Let me know if you have any questions or comments!

**Comment by admoorgit** [comment]
Hello @jrubenoff !
I met with Jeff on Friday and we talked this over. We're both hesitant on the modal approach, and would like to see an alternative — either a full-screen takeover or a drawer. We agree with your approach in keeping it simple and only include the name of chapters, as it could get really busy adding subsections.

As far as styling goes, it looks good overall! A few small suggestions:
- Let's shrink the size of the numbers and circles down so you can tighten things up and get more on the page
- Tweak the styling so underline isn't visible in default state — this'll make it more immediately readable, and it's already clear they're links since they're in a menu
- S'ok to have underline appear on hover, or color change, or whatever makes sense

That's it! Let me know if you have any questions.

**Comment by admoorgit** [comment]
ALSO: Not sure if this is the right thread, but definite YES to having previous/next chapter links persistent at the bottom of the page. Will be wonderful for linear navigation without the need to pop back to the main nav

**Comment by jrubenoff** [comment]
@admoorgit Here's what a drawer / full-screen takeover might look like.

(Note: I moved the "More Guides" links into the dialog to simplify things. Happy to talk about that if you'd like!)

### Drawer on the right

![CleanShot 2023-06-21 at 20 46 32](https://github.com/bloom-works/guides-template/assets/1328849/1fb66d8b-8960-4602-864e-9ae78107b5be)

### Drawer on the left

**Small screens**

<img src="https://github.com/bloom-works/guides-template/assets/1328849/29734fb6-3d83-4583-957d-e3b108fde7d2" alt="" width="400" />

**Large screens**

![CleanShot 2023-06-21 at 20 51 55](https://github.com/bloom-works/guides-template/assets/1328849/19ac0ac0-331e-4bb0-9b61-70faa67c77c1)

### Fullscreen takeover

A **single-column** layout contains an exorbitant amount of whitespace:

![CleanShot 2023-06-21 at 21 00 47@2x](https://github.com/bloom-works/guides-template/assets/1328849/6b1a942f-c37e-4eb7-b2e8-b80e85248fab)

A **grid** layout looks nicer at the expense of scannability:

<img width="1323" alt="CleanShot 2023-06-21 at 21 04 21@2x" src="https://github.com/bloom-works/guides-template/assets/1328849/03377bbc-d796-4060-ac45-3caab8987309">

---

I think the drawer on the left is most effective at maintaining readability while remaining discoverable. But LMK what you prefer!

**Comment by SMakaiTakori** [comment]
@jrubenoff Thanks for sharing the different drawer view options. I agree with you that the grid is less readable and the drawer popping out from the left or the right would be most effective.

**Comment by admoorgit** [comment]
Agree with drawer on left @jrubenoff. Let's make it so on desktop and mobile for consistency. All good w/ logo in the middle.

A thought on "Other guides" in the nav, 1) it may get buried in longer guides and 2) not sure I love having links to other guides altogether paired with current guide links. Wonder if this can live in the footer? Or we make the title itself a sort of "drop down" so you can click that to see the others? May be asking too much. Footer is probably the way to go, knowing we'll have a landing page that lists them all at some point ... which may utilize a grid in some fashion.

@jeffmaher do you have anything to add here?

**Comment by jeffmaher** [comment]
Nothing else to add -- agree with everything Adam said!

**Comment by jeffmaher** [comment]
One tiny fix that @jrubenoff will update on Wed, then over to design and eng for review.

**Comment by SMakaiTakori** [comment]
@jrubenoff Is this complete or do you need more time?

**Comment by jeffmaher** [comment]
Per @SMakaiTakori :

- Makai pinged Josh, and Adam approved fixes
- Going to merge in
